version: '2'


services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:rw
    environment:
      - LETSENCRYPT_TEST=TRUE


  web:
    image: nginx
    container_name: nextcloud_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - proxy-tier


  rclone-mount:
    image: mumiehub/rclone-mount
    container_name: rclone-mount
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    volumes:
      - ./rclone.conf:/config/.rclone.conf
      - ./nextcloud/data_remote:/var/www/html/data:shared
    environment:
      - RemotePath=${RCLONE_REMOTE}
      - MountPoint=/var/www/html/data
      - MountCommands=--max-read-ahead 1024k --transfers 20 --checkers 40 --uid ${MOUNT_UID} --gid ${MOUNT_GID} --allow-other --umask 0007


  app:
    image: nextcloud:11-fpm
    container_name: nextcloud_fpm
    links:
      - db
      - rclone-mount
#    devices:
#      - /dev/fuse
    volumes_from:
      - rclone-mount
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data_local/nextcloud.log:/var/www/html/nextcloud.log
      - ./nextcloud/cache:/var/www/cache
    networks:
      - proxy-tier
    

  db:
    image: mariadb
    container_name: db
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_USER_PW}
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy

