#!/bin/bash -eux

source .env

#Create config
mkdir -p ./nextcloud/config

cat > ./nextcloud/config/config.php <<EOF
<?php
\$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => '${DOMAIN}',
  ),
  'datadirectory' => '/var/www/html/data',
  'cache_path' => '/var/www/cache',
  'overwrite.cli.url' => 'https://${DOMAIN}',
  'dbtype' => 'mysql',
  'dbname' => 'nextcloud',
  'dbhost' => 'db:3306',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '${MYSQL_USER_PW}',
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'logfile' => '/var/www/html/nextcloud.log',
  'loglevel' => '0',
);
EOF


#add proxy config for max_upload_size
mkdir -p ./proxy/conf.d

echo "client_max_body_size 16G;" > ./proxy/conf.d/uploadsize.conf

#create data dirs
mkdir -p ./nextcloud/data_remote
mkdir -p ./nextcloud/data_local/files_external/
touch ./nextcloud/data_local/files_external/rootcerts.crt
touch ./nextcloud/data_local/nextcloud.log
