web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - app
  volumes_from:
    - app
  ports:
    - 80:80

app:
  image: nextcloud:11-fpm
  links:
    - db
  volumes:
    - ./nextcloud/apps:/var/www/html/apps
    - ./nextcloud/config:/var/www/html/config
    - ./nextcloud/data_acd:/var/www/html/data
    - ./nextcloud/cache:/var/www/html/cache

db:
  image: mysql
  volumes:
    - ./nextcloud/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=${MYSQL_USER_PW}
    - MYSQL_DATABASE=nextcloud
