version: '2'

networks:
  proxy:

volumes:
  apps:
  config:
  data:
  db:
  certs:


services:
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./upload_limit.conf:/etc/nginx/conf.d/upload_limit.conf
    networks:
      - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
    networks:
      - proxy


  app:
    image: nextcloud:apache
    restart: always
    links: 
      - db
      - redis
    volumes:
      - apps:/var/www/html/apps
      - config:/var/www/html/config
      - ./config.php:/var/www/html/config/config.php
      - data:/var/www/html/data
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - default
      - proxy
    

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_USER_PW}

  redis:
    image: redis
    restart: always

  collabora:
    image: collabora/code
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - domain=${DOMAIN}
      - VIRTUAL_HOST=${COLLABORA_DOMAIN}
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=${COLLABORA_DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - proxy
    restart: always
